obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01
inflation_radius: 0.7
observation_sources: FrontLaserScan VelodynePointCloud
FrontLaserScan:     {data_type: LaserScan,   topic: /lidar/scan,       marking: true, clearing: true}
VelodynePointCloud: {data_type: PointCloud2, topic: /velodyne_points,  marking: true, clearing: true}
