qpOASES3.0beta: SolutionAnalysis Class Reference
SolutionAnalysis Class Reference
Provides additional tools for analysing QP solutions.
#include <SolutionAnalysis.hpp>
Public Member Functions
SolutionAnalysis ()
SolutionAnalysis (const SolutionAnalysis &rhs)
~SolutionAnalysis ()
SolutionAnalysis & operator= (const SolutionAnalysis &rhs)
returnValue getMaxKKTviolation (QProblemB *qp, real_t &maxKKTviolation) const
returnValue getMaxKKTviolation (QProblem *qp, real_t &maxKKTviolation) const
returnValue getMaxKKTviolation (SQProblem *qp, real_t &maxKKTviolation) const
returnValue getVarianceCovariance (QProblemB *qp, real_t *g_b_bA_VAR, real_t *Primal_Dual_VAR) const
returnValue getVarianceCovariance (QProblem *qp, real_t *g_b_bA_VAR, real_t *Primal_Dual_VAR) const
returnValue getVarianceCovariance (SQProblem *qp, real_t *g_b_bA_VAR, real_t *Primal_Dual_VAR) const
Detailed Description
This class is intended to provide additional tools for analysing a QP solution obtained with qpOASES.
Author:
Boris Houska, Hans Joachim Ferreau
Version:
3.0beta
Date:
2007-2011
Constructor & Destructor Documentation
BEGIN_NAMESPACE_QPOASES SolutionAnalysis::SolutionAnalysis ()
Default constructor.
SolutionAnalysis::SolutionAnalysis (const SolutionAnalysis & rhs)
Copy constructor (deep copy).
Parameters:
rhs Rhs object.
SolutionAnalysis::~SolutionAnalysis ()
Destructor.
Member Function Documentation
returnValue SolutionAnalysis::getMaxKKTviolation (SQProblem * qp, real_t & maxKKTviolation) const
Determines the maximum violation of the KKT optimality conditions of the current iterate within the SQProblem object.
Returns:
SUCCESSFUL_RETURN
RET_UNABLE_TO_ANALYSE_QPROBLEM
Parameters:
qp SQProblem to be analysed.
maxKKTviolation OUTPUT: maximum violation of the KKT conditions.
References getMaxKKTviolation().
returnValue SolutionAnalysis::getMaxKKTviolation (QProblem * qp, real_t & maxKKTviolation) const
Determines the maximum violation of the KKT optimality conditions of the current iterate within the QProblem object.
Returns:
SUCCESSFUL_RETURN
RET_UNABLE_TO_ANALYSE_QPROBLEM
Parameters:
qp QProblem to be analysed.
maxKKTviolation OUTPUT: maximum violation of the KKT conditions.
References QProblem::A, QProblemB::bounds, QProblem::constraints, QProblemB::g, QProblemB::getHessianType(), QProblem::getNC(), QProblemB::getNV(), SubjectTo::getStatus(), QProblemB::H, HST_IDENTITY, HST_ZERO, QProblemB::lb, QProblem::lbA, real_t, ST_LOWER, ST_UPPER, SUCCESSFUL_RETURN, Matrix::times(), Matrix::transTimes(), QProblemB::ub, QProblem::ubA, QProblemB::x, and QProblemB::y.
returnValue SolutionAnalysis::getMaxKKTviolation (QProblemB * qp, real_t & maxKKTviolation) const
Determines the maximum violation of the KKT optimality conditions of the current iterate within the QProblemB object.
Returns:
SUCCESSFUL_RETURN
RET_UNABLE_TO_ANALYSE_QPROBLEM
Parameters:
qp QProblemB to be analysed.
maxKKTviolation OUTPUT: maximum violation of the KKT conditions.
References QProblemB::bounds, QProblemB::g, QProblemB::getHessianType(), QProblemB::getNV(), SubjectTo::getStatus(), QProblemB::H, HST_IDENTITY, HST_ZERO, QProblemB::lb, real_t, ST_LOWER, ST_UPPER, SUCCESSFUL_RETURN, Matrix::times(), QProblemB::ub, QProblemB::x, and QProblemB::y.
Referenced by getMaxKKTviolation().
returnValue SolutionAnalysis::getVarianceCovariance (SQProblem * qp, real_t * g_b_bA_VAR, real_t * Primal_Dual_VAR) const
Computes the variance-covariance matrix of the QP output for uncertain
inputs.
Returns:
SUCCESSFUL_RETURN
RET_HOTSTART_FAILED
RET_STEPDIRECTION_FAILED_TQ
RET_STEPDIRECTION_FAILED_CHOLESKY
Parameters:
qp SQProblem to be analysed.
g_b_bA_VAR INPUT : Variance-covariance of g, the bounds lb and ub, and lbA and ubA respectively. Dimension: (2nV+nC) x (2nV+nC)
Primal_Dual_VAR OUTPUT: The result for the variance-covariance of the primal and dual variables. Dimension: (2nV+nC) x (2nV+nC)
References getVarianceCovariance().
returnValue SolutionAnalysis::getVarianceCovariance (QProblem * qp, real_t * g_b_bA_VAR, real_t * Primal_Dual_VAR) const
Computes the variance-covariance matrix of the QP output for uncertain
inputs.
Returns:
SUCCESSFUL_RETURN
RET_HOTSTART_FAILED
RET_STEPDIRECTION_FAILED_TQ
RET_STEPDIRECTION_FAILED_CHOLESKY
Parameters:
qp QProblem to be analysed.
g_b_bA_VAR INPUT : Variance-covariance of g, the bounds lb and ub, and lbA and ubA respectively. Dimension: (2nV+nC) x (2nV+nC)
Primal_Dual_VAR OUTPUT: The result for the variance-covariance of the primal and dual variables. Dimension: (2nV+nC) x (2nV+nC)
References QProblemB::bounds, BT_FALSE, QProblem::constraints, QProblem::determineStepDirection(), Constraints::getActive(), Bounds::getFixed(), Bounds::getFree(), QProblem::getNAC(), QProblem::getNC(), QProblemB::getNFR(), QProblemB::getNFX(), Indexlist::getNumberArray(), QProblemB::getNV(), real_t, RET_HOTSTART_FAILED, RET_STEPDIRECTION_DETERMINATION_FAILED, SUCCESSFUL_RETURN, and THROWERROR.
returnValue SolutionAnalysis::getVarianceCovariance (QProblemB * qp, real_t * g_b_bA_VAR, real_t * Primal_Dual_VAR) const
Computes the variance-covariance matrix of the QP output for uncertain
inputs.
Returns:
SUCCESSFUL_RETURN
RET_HOTSTART_FAILED
RET_STEPDIRECTION_FAILED_TQ
RET_STEPDIRECTION_FAILED_CHOLESKY
Parameters:
qp QProblemB to be analysed.
g_b_bA_VAR INPUT : Variance-covariance of g, the bounds lb and ub, and lbA and ubA respectively. Dimension: 2nV x 2nV
Primal_Dual_VAR OUTPUT: The result for the variance-covariance of the primal and dual variables. Dimension: 2nV x 2nV
References RET_NOT_YET_IMPLEMENTED, and THROWERROR.
Referenced by getVarianceCovariance().
SolutionAnalysis & SolutionAnalysis::operator= (const SolutionAnalysis & rhs)
Copy asingment operator (deep copy).
Parameters:
rhs Rhs object.
The documentation for this class was generated from the following files:
include/qpOASES/extras/SolutionAnalysis.hpp
src/extras/SolutionAnalysis.cpp