qpOASES3.0beta: SymSparseMat Class Reference
SymSparseMat Class Reference
Interfaces matrix-vector operations tailored to symmetric sparse matrices.
#include <Matrices.hpp>
Public Member Functions
SymSparseMat ()
SymSparseMat (int nr, int nc, sparse_int_t *r, sparse_int_t *c, real_t *v, sparse_int_t *d=0)
SymSparseMat (int nr, int nc, int ld, const real_t *const v)
virtual Matrix * duplicate () const
virtual returnValue bilinear (const Indexlist *const icols, int xN, const real_t *x, int xLD, real_t *y, int yLD) const
virtual void free ()=0
virtual real_t diag (int i) const =0
virtual BooleanType isDiag () const =0
virtual real_t getNorm () const =0
virtual real_t getRowNorm (int rNum) const =0
virtual returnValue getRow (int rNum, const Indexlist *const icols, real_t alpha, real_t *row) const =0
virtual returnValue getCol (int cNum, const Indexlist *const irows, real_t alpha, real_t *col) const =0
virtual returnValue times (int xN, real_t alpha, const real_t *x, int xLD, real_t beta, real_t *y, int yLD) const =0
virtual returnValue times (const Indexlist *const irows, const Indexlist *const icols, int xN, real_t alpha, const real_t *x, int xLD, real_t beta, real_t *y, int yLD, BooleanType yCompr=BT_TRUE) const =0
virtual returnValue transTimes (int xN, real_t alpha, const real_t *x, int xLD, real_t beta, real_t *y, int yLD) const =0
virtual returnValue transTimes (const Indexlist *const irows, const Indexlist *const icols, int xN, real_t alpha, const real_t *x, int xLD, real_t beta, real_t *y, int yLD) const =0
virtual returnValue addToDiag (real_t alpha)=0
virtual returnValue print () const =0
BooleanType needToFreeMemory () const
void doFreeMemory ()
void doNotFreeMemory ()
virtual void free ()
virtual real_t diag (int i) const
virtual BooleanType isDiag () const
virtual real_t getNorm () const
virtual real_t getRowNorm (int rNum) const
virtual returnValue getRow (int rNum, const Indexlist *const icols, real_t alpha, real_t *row) const
virtual returnValue getCol (int cNum, const Indexlist *const irows, real_t alpha, real_t *col) const
virtual returnValue times (int xN, real_t alpha, const real_t *x, int xLD, real_t beta, real_t *y, int yLD) const
virtual returnValue times (const Indexlist *const irows, const Indexlist *const icols, int xN, real_t alpha, const real_t *x, int xLD, real_t beta, real_t *y, int yLD, BooleanType yCompr=BT_TRUE) const
virtual returnValue transTimes (int xN, real_t alpha, const real_t *x, int xLD, real_t beta, real_t *y, int yLD) const
virtual returnValue transTimes (const Indexlist *const irows, const Indexlist *const icols, int xN, real_t alpha, const real_t *x, int xLD, real_t beta, real_t *y, int yLD) const
virtual returnValue addToDiag (real_t alpha)
sparse_int_t * createDiagInfo ()
real_t * full () const
virtual returnValue print () const
Protected Attributes
BooleanType freeMemory
int nRows
int nCols
sparse_int_t * ir
sparse_int_t * jc
sparse_int_t * jd
real_t * val
Detailed Description
Symmetric sparse matrix class (column compressed format).
Author:
Andreas Potschka, Christian Kirches, Hans Joachim Ferreau
Version:
3.0beta
Date:
2011
Constructor & Destructor Documentation
SymSparseMat::SymSparseMat () [inline]
Default constructor.
SymSparseMat::SymSparseMat (int nr, int nc, sparse_int_t * r, sparse_int_t * c, real_t * v, sparse_int_t * d = 0) [inline]
Constructor with arguments.
Parameters:
nr Number of rows.
nc Number of columns.
r Row indices (length).
c Indices to first entry of columns (nCols+1).
v Vector of entries (length).
d Indices to first entry of lower triangle (including diagonal) (nCols).
SymSparseMat::SymSparseMat (int nr, int nc, int ld, const real_t *const v) [inline]
Constructor from dense matrix.
Parameters:
nr Number of rows.
nc Number of columns.
ld Leading dimension.
v Row major stored matrix elements.
Member Function Documentation
returnValue SparseMatrix::addToDiag (real_t alpha) [virtual, inherited]
Adds given offset to diagonal of matrix.
Returns:
SUCCESSFUL_RETURN
RET_NO_DIAGONAL_AVAILABLE
Parameters:
alpha Diagonal offset.
Implements Matrix.
References SparseMatrix::ir, SparseMatrix::jd, SparseMatrix::nCols, SparseMatrix::nRows, RET_NO_DIAGONAL_AVAILABLE, SUCCESSFUL_RETURN, and SparseMatrix::val.
virtual returnValue Matrix::addToDiag (real_t alpha) [pure virtual, inherited]
Adds given offset to diagonal of matrix.
Returns:
SUCCESSFUL_RETURN
RET_NO_DIAGONAL_AVAILABLE
Parameters:
alpha Diagonal offset.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblemB::regulariseHessian().
returnValue SymSparseMat::bilinear (const Indexlist *const icols, int xN, const real_t * x, int xLD, real_t * y, int yLD) const [virtual]
Compute bilinear form y = x'*H*x using submatrix given by index list.
Returns:
SUCCESSFUL_RETURN
Parameters:
icols Index list specifying columns of x.
xN Number of vectors to multiply.
x Input vector to be multiplied (uncompressed).
xLD Leading dimension of input x.
y Output vector of results (compressed).
yLD Leading dimension of output y.
Implements SymmetricMatrix.
References SparseMatrix::ir, Indexlist::iSort, SparseMatrix::jc, SparseMatrix::jd, Indexlist::length, Indexlist::number, SUCCESSFUL_RETURN, and SparseMatrix::val.
sparse_int_t * SparseMatrix::createDiagInfo () [inherited]
Create jd field from ir and jc.
Returns:
Pointer to jd.
References SparseMatrix::ir, SparseMatrix::jc, SparseMatrix::jd, and SparseMatrix::nCols.
Referenced by solveOQPbenchmark().
real_t SparseMatrix::diag (int i) const [virtual, inherited]
Returns i-th diagonal entry.
Returns:
i-th diagonal entry
Parameters:
i Index.
Implements Matrix.
References SparseMatrix::ir, SparseMatrix::jc, SparseMatrix::jd, and SparseMatrix::val.
virtual real_t Matrix::diag (int i) const [pure virtual, inherited]
Returns i-th diagonal entry.
Returns:
i-th diagonal entry
Parameters:
i Index.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblemB::determineHessianType(), QProblemB::removeBound(), and QProblem::removeBound().
void Matrix::doFreeMemory () [inline, inherited]
Enables de-allocation of internal memory.
References BT_TRUE, and Matrix::freeMemory.
Referenced by duplicate(), SparseMatrixRow::duplicate(), SparseMatrix::duplicate(), SymDenseMat::duplicate(), DenseMatrix::duplicate(), QProblemB::setupQPdataFromFile(), QProblem::setupQPdataFromFile(), SparseMatrix::SparseMatrix(), and SparseMatrixRow::SparseMatrixRow().
void Matrix::doNotFreeMemory () [inline, inherited]
Disables de-allocation of internal memory.
Referenced by SparseMatrixRow::free(), SparseMatrix::free(), Matrix::Matrix(), SparseMatrix::SparseMatrix(), and SparseMatrixRow::SparseMatrixRow().
Matrix * SymSparseMat::duplicate () const [virtual]
Returns a deep-copy of the Matrix object.
Returns:
Deep-copy of Matrix object
Reimplemented from SparseMatrix.
References Matrix::doFreeMemory(), SparseMatrix::ir, SparseMatrix::jc, SparseMatrix::jd, SparseMatrix::nCols, SparseMatrix::nRows, real_t, and SparseMatrix::val.
void SparseMatrix::free () [virtual, inherited]
Frees all internal memory.
Implements Matrix.
References Matrix::doNotFreeMemory(), SparseMatrix::ir, SparseMatrix::jc, SparseMatrix::jd, and SparseMatrix::val.
Referenced by SparseMatrix::~SparseMatrix().
virtual void Matrix::free () [pure virtual, inherited]
Frees all internal memory.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
real_t * SparseMatrix::full () const [inherited]
Allocate and create dense matrix in row major format.
Returns:
Pointer to matrix array.
References SparseMatrix::ir, SparseMatrix::jc, SparseMatrix::nCols, SparseMatrix::nRows, real_t, and SparseMatrix::val.
returnValue SparseMatrix::getCol (int cNum, const Indexlist *const irows, real_t alpha, real_t * col) const [virtual, inherited]
Retrieve indexed entries of matrix column multiplied by alpha.
Parameters:
cNum Column number.
irows Index list specifying rows.
alpha Scalar factor.
col Output column vector.
Implements Matrix.
References SparseMatrix::ir, Indexlist::iSort, SparseMatrix::jc, Indexlist::number, SUCCESSFUL_RETURN, and SparseMatrix::val.
virtual returnValue Matrix::getCol (int cNum, const Indexlist *const irows, real_t alpha, real_t * col) const [pure virtual, inherited]
Retrieve indexed entries of matrix column multiplied by alpha.
Returns:
SUCCESSFUL_RETURN
Parameters:
cNum Column number.
irows Index list specifying rows.
alpha Scalar factor.
col Output column vector.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblem::removeBound(), QProblemB::setupCholeskyDecomposition(), and QProblem::setupCholeskyDecompositionProjected().
real_t SparseMatrix::getNorm () const [virtual, inherited]
Get the two-norm of the matrix
Returns:
Two-norm of the matrix
Implements Matrix.
virtual real_t Matrix::getNorm () const [pure virtual, inherited]
Get the two-norm of the matrix
Returns:
Two-norm of the matrix
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblemB::regulariseHessian().
returnValue SparseMatrix::getRow (int rNum, const Indexlist *const icols, real_t alpha, real_t * row) const [virtual, inherited]
Retrieve indexed entries of matrix row multiplied by alpha.
Parameters:
rNum Row number.
icols Index list specifying columns.
alpha Scalar factor.
row Output row vector.
Implements Matrix.
References SparseMatrix::ir, Indexlist::iSort, SparseMatrix::jc, Indexlist::length, SparseMatrix::nCols, Indexlist::number, SUCCESSFUL_RETURN, and SparseMatrix::val.
virtual returnValue Matrix::getRow (int rNum, const Indexlist *const icols, real_t alpha, real_t * row) const [pure virtual, inherited]
Retrieve indexed entries of matrix row multiplied by alpha.
Returns:
SUCCESSFUL_RETURN
Parameters:
rNum Row number.
icols Index list specifying columns.
alpha Scalar factor.
row Output row vector.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblem::addConstraint(), QProblem::addConstraint_checkLI(), QProblem::addConstraint_ensureLI(), and QProblemB::removeBound().
real_t SparseMatrix::getRowNorm (int rNum) const [virtual, inherited]
Get the two-norm of a row
Returns:
Two-norm of row rNum
Implements Matrix.
References SparseMatrix::ir, SparseMatrix::jc, SparseMatrix::nCols, real_t, and SparseMatrix::val.
virtual real_t Matrix::getRowNorm (int rNum) const [pure virtual, inherited]
Get the two-norm of a row
Returns:
Two-norm of row rNum
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblem::setA().
BooleanType SparseMatrix::isDiag () const [virtual, inherited]
Checks whether matrix is square and diagonal.
Returns:
BT_TRUE iff matrix is square and diagonal;
BT_FALSE otherwise.
Implements Matrix.
References BT_FALSE.
virtual BooleanType Matrix::isDiag () const [pure virtual, inherited]
Checks whether matrix is square and diagonal.
Returns:
BT_TRUE iff matrix is square and diagonal;
BT_FALSE otherwise.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblemB::determineHessianType().
BooleanType Matrix::needToFreeMemory () const [inline, inherited]
Returns whether internal memory needs to be de-allocated.
Returns:
BT_TRUE iff internal memory needs to be de-allocated,
BT_FALSE otherwise
References Matrix::freeMemory.
Referenced by SymDenseMat::duplicate(), DenseMatrix::duplicate(), DenseMatrix::~DenseMatrix(), SparseMatrix::~SparseMatrix(), and SparseMatrixRow::~SparseMatrixRow().
returnValue SparseMatrix::print () const [virtual, inherited]
Prints matrix to screen.
Returns:
RET_NOT_YET_IMPLEMENTED
Implements Matrix.
References RET_NOT_YET_IMPLEMENTED, and THROWERROR.
virtual returnValue Matrix::print () const [pure virtual, inherited]
Prints matrix to screen.
Returns:
SUCCESSFUL_RETURN
RET_NOT_YET_IMPLEMENTED
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
returnValue SparseMatrix::times (const Indexlist *const irows, const Indexlist *const icols, int xN, real_t alpha, const real_t * x, int xLD, real_t beta, real_t * y, int yLD, BooleanType yCompr = BT_TRUE) const [virtual, inherited]
Evaluate matrix vector product with submatrix given by Indexlist.
Parameters:
irows Index list specifying rows.
icols Index list specifying columns.
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
yCompr Compressed storage for y.
Implements Matrix.
References BT_TRUE, SparseMatrix::ir, Indexlist::iSort, SparseMatrix::jc, Indexlist::length, SparseMatrix::nCols, Indexlist::number, SUCCESSFUL_RETURN, and SparseMatrix::val.
returnValue SparseMatrix::times (int xN, real_t alpha, const real_t * x, int xLD, real_t beta, real_t * y, int yLD) const [virtual, inherited]
Evaluate Y=alpha*A*X + beta*Y.
Parameters:
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
Implements Matrix.
References SparseMatrix::ir, SparseMatrix::jc, SparseMatrix::nCols, SparseMatrix::nRows, SUCCESSFUL_RETURN, and SparseMatrix::val.
virtual returnValue Matrix::times (const Indexlist *const irows, const Indexlist *const icols, int xN, real_t alpha, const real_t * x, int xLD, real_t beta, real_t * y, int yLD, BooleanType yCompr = BT_TRUE) const [pure virtual, inherited]
Evaluate matrix vector product with submatrix given by Indexlist.
Returns:
SUCCESSFUL_RETURN
Parameters:
irows Index list specifying rows.
icols Index list specifying columns.
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
yCompr Compressed storage for y.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
virtual returnValue Matrix::times (int xN, real_t alpha, const real_t * x, int xLD, real_t beta, real_t * y, int yLD) const [pure virtual, inherited]
Evaluate Y=alpha*A*X + beta*Y.
Returns:
SUCCESSFUL_RETURN
Parameters:
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblemB::determineStepDirection(), QProblem::determineStepDirection(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getMaxKKTviolation(), QProblemB::getObjVal(), QProblem::performStep(), QProblem::removeBound(), QProblem::removeConstraint(), QProblem::setA(), QProblem::setupAuxiliaryQP(), QProblemB::setupAuxiliaryQPgradient(), QProblem::setupAuxiliaryQPgradient(), QProblem::setupAuxiliaryQPsolution(), and QProblem::solveQP().
returnValue SparseMatrix::transTimes (const Indexlist *const irows, const Indexlist *const icols, int xN, real_t alpha, const real_t * x, int xLD, real_t beta, real_t * y, int yLD) const [virtual, inherited]
Evaluate matrix transpose vector product.
Parameters:
irows Index list specifying rows.
icols Index list specifying columns.
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
Implements Matrix.
References SparseMatrix::ir, Indexlist::iSort, SparseMatrix::jc, Indexlist::length, Indexlist::number, SUCCESSFUL_RETURN, and SparseMatrix::val.
returnValue SparseMatrix::transTimes (int xN, real_t alpha, const real_t * x, int xLD, real_t beta, real_t * y, int yLD) const [virtual, inherited]
Evaluate Y=alpha*A'*X + beta*Y.
Parameters:
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
Implements Matrix.
References SparseMatrix::ir, SparseMatrix::jc, SparseMatrix::nCols, SUCCESSFUL_RETURN, and SparseMatrix::val.
virtual returnValue Matrix::transTimes (const Indexlist *const irows, const Indexlist *const icols, int xN, real_t alpha, const real_t * x, int xLD, real_t beta, real_t * y, int yLD) const [pure virtual, inherited]
Evaluate matrix transpose vector product.
Returns:
SUCCESSFUL_RETURN
Parameters:
irows Index list specifying rows.
icols Index list specifying columns.
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
virtual returnValue Matrix::transTimes (int xN, real_t alpha, const real_t * x, int xLD, real_t beta, real_t * y, int yLD) const [pure virtual, inherited]
Evaluate Y=alpha*A'*X + beta*Y.
Returns:
SUCCESSFUL_RETURN
Parameters:
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblem::addBound_ensureLI(), QProblem::addConstraint_ensureLI(), QProblem::determineStepDirection(), SolutionAnalysis::getMaxKKTviolation(), QProblem::setupAuxiliaryQPgradient(), and QProblem::solveQP().
Member Data Documentation
BooleanType Matrix::freeMemory [protected, inherited]
Indicating whether internal memory needs to be de-allocated.
Referenced by Matrix::doFreeMemory(), and Matrix::needToFreeMemory().
sparse_int_t* SparseMatrix::ir [protected, inherited]
Row indices (length).
Referenced by SparseMatrix::addToDiag(), bilinear(), SparseMatrix::createDiagInfo(), SparseMatrix::diag(), duplicate(), SparseMatrix::duplicate(), SparseMatrix::free(), SparseMatrix::full(), SparseMatrix::getCol(), SparseMatrix::getRow(), SparseMatrix::getRowNorm(), SparseMatrix::SparseMatrix(), SparseMatrix::times(), and SparseMatrix::transTimes().
sparse_int_t* SparseMatrix::jc [protected, inherited]
Indices to first entry of columns (nCols+1).
Referenced by bilinear(), SparseMatrix::createDiagInfo(), SparseMatrix::diag(), duplicate(), SparseMatrix::duplicate(), SparseMatrix::free(), SparseMatrix::full(), SparseMatrix::getCol(), SparseMatrix::getRow(), SparseMatrix::getRowNorm(), SparseMatrix::SparseMatrix(), SparseMatrix::times(), and SparseMatrix::transTimes().
sparse_int_t* SparseMatrix::jd [protected, inherited]
Indices to first entry of lower triangle (including diagonal) (nCols).
Referenced by SparseMatrix::addToDiag(), bilinear(), SparseMatrix::createDiagInfo(), SparseMatrix::diag(), duplicate(), SparseMatrix::duplicate(), and SparseMatrix::free().
int SparseMatrix::nCols [protected, inherited]
Number of columns.
Referenced by SparseMatrix::addToDiag(), SparseMatrix::createDiagInfo(), duplicate(), SparseMatrix::duplicate(), SparseMatrix::full(), SparseMatrix::getRow(), SparseMatrix::getRowNorm(), SparseMatrix::SparseMatrix(), SparseMatrix::times(), and SparseMatrix::transTimes().
int SparseMatrix::nRows [protected, inherited]
Number of rows.
Referenced by SparseMatrix::addToDiag(), duplicate(), SparseMatrix::duplicate(), SparseMatrix::full(), SparseMatrix::SparseMatrix(), and SparseMatrix::times().
real_t* SparseMatrix::val [protected, inherited]
Vector of entries (length).
Referenced by SparseMatrix::addToDiag(), bilinear(), SparseMatrix::diag(), duplicate(), SparseMatrix::duplicate(), SparseMatrix::free(), SparseMatrix::full(), SparseMatrix::getCol(), SparseMatrix::getRow(), SparseMatrix::getRowNorm(), SparseMatrix::SparseMatrix(), SparseMatrix::times(), and SparseMatrix::transTimes().
The documentation for this class was generated from the following files:
include/qpOASES/Matrices.hpp
src/Matrices.cpp