qpOASES3.0beta: SymmetricMatrix Class Reference
SymmetricMatrix Class Reference
Abstract base class for interfacing matrix-vector operations tailored to symmetric matrices.
#include <Matrices.hpp>
Public Member Functions
virtual returnValue bilinear (const Indexlist *const icols, int xN, const real_t *x, int xLD, real_t *y, int yLD) const =0
virtual void free ()=0
virtual Matrix * duplicate () const =0
virtual real_t diag (int i) const =0
virtual BooleanType isDiag () const =0
virtual real_t getNorm () const =0
virtual real_t getRowNorm (int rNum) const =0
virtual returnValue getRow (int rNum, const Indexlist *const icols, real_t alpha, real_t *row) const =0
virtual returnValue getCol (int cNum, const Indexlist *const irows, real_t alpha, real_t *col) const =0
virtual returnValue times (int xN, real_t alpha, const real_t *x, int xLD, real_t beta, real_t *y, int yLD) const =0
virtual returnValue times (const Indexlist *const irows, const Indexlist *const icols, int xN, real_t alpha, const real_t *x, int xLD, real_t beta, real_t *y, int yLD, BooleanType yCompr=BT_TRUE) const =0
virtual returnValue transTimes (int xN, real_t alpha, const real_t *x, int xLD, real_t beta, real_t *y, int yLD) const =0
virtual returnValue transTimes (const Indexlist *const irows, const Indexlist *const icols, int xN, real_t alpha, const real_t *x, int xLD, real_t beta, real_t *y, int yLD) const =0
virtual returnValue addToDiag (real_t alpha)=0
virtual returnValue print () const =0
BooleanType needToFreeMemory () const
void doFreeMemory ()
void doNotFreeMemory ()
Protected Attributes
BooleanType freeMemory
Detailed Description
Abstract base class for symmetric matrices. Extends Matrix interface with bilinear form evaluation.
Author:
Andreas Potschka, Christian Kirches, Hans Joachim Ferreau
Version:
3.0beta
Date:
2011
Member Function Documentation
virtual returnValue Matrix::addToDiag (real_t alpha) [pure virtual, inherited]
Adds given offset to diagonal of matrix.
Returns:
SUCCESSFUL_RETURN
RET_NO_DIAGONAL_AVAILABLE
Parameters:
alpha Diagonal offset.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblemB::regulariseHessian().
virtual returnValue SymmetricMatrix::bilinear (const Indexlist *const icols, int xN, const real_t * x, int xLD, real_t * y, int yLD) const [pure virtual]
Compute bilinear form y = x'*H*x using submatrix given by index list.
Returns:
SUCCESSFUL_RETURN
Parameters:
icols Index list specifying columns of x.
xN Number of vectors to multiply.
x Input vector to be multiplied (uncompressed).
xLD Leading dimension of input x.
y Output vector of results (compressed).
yLD Leading dimension of output y.
Implemented in SymDenseMat, and SymSparseMat.
Referenced by QProblem::setupCholeskyDecompositionProjected().
virtual real_t Matrix::diag (int i) const [pure virtual, inherited]
Returns i-th diagonal entry.
Returns:
i-th diagonal entry
Parameters:
i Index.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblemB::determineHessianType(), QProblemB::removeBound(), and QProblem::removeBound().
void Matrix::doFreeMemory () [inline, inherited]
Enables de-allocation of internal memory.
References BT_TRUE, and Matrix::freeMemory.
Referenced by SymSparseMat::duplicate(), SparseMatrixRow::duplicate(), SparseMatrix::duplicate(), SymDenseMat::duplicate(), DenseMatrix::duplicate(), QProblemB::setupQPdataFromFile(), QProblem::setupQPdataFromFile(), SparseMatrix::SparseMatrix(), and SparseMatrixRow::SparseMatrixRow().
void Matrix::doNotFreeMemory () [inline, inherited]
Disables de-allocation of internal memory.
Referenced by SparseMatrixRow::free(), SparseMatrix::free(), Matrix::Matrix(), SparseMatrix::SparseMatrix(), and SparseMatrixRow::SparseMatrixRow().
virtual Matrix* Matrix::duplicate () const [pure virtual, inherited]
Returns a deep-copy of the Matrix object.
Returns:
Deep-copy of Matrix object
Implemented in DenseMatrix, SymDenseMat, SparseMatrix, SparseMatrixRow, and SymSparseMat.
Referenced by QProblemB::copy(), and QProblem::copy().
virtual void Matrix::free () [pure virtual, inherited]
Frees all internal memory.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
virtual returnValue Matrix::getCol (int cNum, const Indexlist *const irows, real_t alpha, real_t * col) const [pure virtual, inherited]
Retrieve indexed entries of matrix column multiplied by alpha.
Returns:
SUCCESSFUL_RETURN
Parameters:
cNum Column number.
irows Index list specifying rows.
alpha Scalar factor.
col Output column vector.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblem::removeBound(), QProblemB::setupCholeskyDecomposition(), and QProblem::setupCholeskyDecompositionProjected().
virtual real_t Matrix::getNorm () const [pure virtual, inherited]
Get the two-norm of the matrix
Returns:
Two-norm of the matrix
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblemB::regulariseHessian().
virtual returnValue Matrix::getRow (int rNum, const Indexlist *const icols, real_t alpha, real_t * row) const [pure virtual, inherited]
Retrieve indexed entries of matrix row multiplied by alpha.
Returns:
SUCCESSFUL_RETURN
Parameters:
rNum Row number.
icols Index list specifying columns.
alpha Scalar factor.
row Output row vector.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblem::addConstraint(), QProblem::addConstraint_checkLI(), QProblem::addConstraint_ensureLI(), and QProblemB::removeBound().
virtual real_t Matrix::getRowNorm (int rNum) const [pure virtual, inherited]
Get the two-norm of a row
Returns:
Two-norm of row rNum
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblem::setA().
virtual BooleanType Matrix::isDiag () const [pure virtual, inherited]
Checks whether matrix is square and diagonal.
Returns:
BT_TRUE iff matrix is square and diagonal;
BT_FALSE otherwise.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblemB::determineHessianType().
BooleanType Matrix::needToFreeMemory () const [inline, inherited]
Returns whether internal memory needs to be de-allocated.
Returns:
BT_TRUE iff internal memory needs to be de-allocated,
BT_FALSE otherwise
References Matrix::freeMemory.
Referenced by SymDenseMat::duplicate(), DenseMatrix::duplicate(), DenseMatrix::~DenseMatrix(), SparseMatrix::~SparseMatrix(), and SparseMatrixRow::~SparseMatrixRow().
virtual returnValue Matrix::print () const [pure virtual, inherited]
Prints matrix to screen.
Returns:
SUCCESSFUL_RETURN
RET_NOT_YET_IMPLEMENTED
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
virtual returnValue Matrix::times (const Indexlist *const irows, const Indexlist *const icols, int xN, real_t alpha, const real_t * x, int xLD, real_t beta, real_t * y, int yLD, BooleanType yCompr = BT_TRUE) const [pure virtual, inherited]
Evaluate matrix vector product with submatrix given by Indexlist.
Returns:
SUCCESSFUL_RETURN
Parameters:
irows Index list specifying rows.
icols Index list specifying columns.
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
yCompr Compressed storage for y.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
virtual returnValue Matrix::times (int xN, real_t alpha, const real_t * x, int xLD, real_t beta, real_t * y, int yLD) const [pure virtual, inherited]
Evaluate Y=alpha*A*X + beta*Y.
Returns:
SUCCESSFUL_RETURN
Parameters:
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblemB::determineStepDirection(), QProblem::determineStepDirection(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getMaxKKTviolation(), QProblemB::getObjVal(), QProblem::performStep(), QProblem::removeBound(), QProblem::removeConstraint(), QProblem::setA(), QProblem::setupAuxiliaryQP(), QProblemB::setupAuxiliaryQPgradient(), QProblem::setupAuxiliaryQPgradient(), QProblem::setupAuxiliaryQPsolution(), and QProblem::solveQP().
virtual returnValue Matrix::transTimes (const Indexlist *const irows, const Indexlist *const icols, int xN, real_t alpha, const real_t * x, int xLD, real_t beta, real_t * y, int yLD) const [pure virtual, inherited]
Evaluate matrix transpose vector product.
Returns:
SUCCESSFUL_RETURN
Parameters:
irows Index list specifying rows.
icols Index list specifying columns.
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
virtual returnValue Matrix::transTimes (int xN, real_t alpha, const real_t * x, int xLD, real_t beta, real_t * y, int yLD) const [pure virtual, inherited]
Evaluate Y=alpha*A'*X + beta*Y.
Returns:
SUCCESSFUL_RETURN
Parameters:
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
Implemented in DenseMatrix, SparseMatrix, and SparseMatrixRow.
Referenced by QProblem::addBound_ensureLI(), QProblem::addConstraint_ensureLI(), QProblem::determineStepDirection(), SolutionAnalysis::getMaxKKTviolation(), QProblem::setupAuxiliaryQPgradient(), and QProblem::solveQP().
Member Data Documentation
BooleanType Matrix::freeMemory [protected, inherited]
Indicating whether internal memory needs to be de-allocated.
Referenced by Matrix::doFreeMemory(), and Matrix::needToFreeMemory().
The documentation for this class was generated from the following file:
include/qpOASES/Matrices.hpp