qpOASES3.0beta: SymDenseMat Class Reference
SymDenseMat Class Reference
Interfaces matrix-vector operations tailored to symmetric dense matrices.
#include <Matrices.hpp>
Public Member Functions
SymDenseMat ()
SymDenseMat (int m, int n, int lD, real_t *v)
virtual Matrix * duplicate () const
virtual returnValue bilinear (const Indexlist *const icols, int xN, const real_t *x, int xLD, real_t *y, int yLD) const
virtual void free ()
virtual real_t diag (int i) const
virtual BooleanType isDiag () const
virtual real_t getNorm () const
virtual real_t getRowNorm (int rNum) const
virtual returnValue getRow (int rNum, const Indexlist *const icols, real_t alpha, real_t *row) const
virtual returnValue getCol (int cNum, const Indexlist *const irows, real_t alpha, real_t *col) const
returnValue times (int xN, real_t alpha, const real_t *x, int xLD, real_t beta, real_t *y, int yLD) const
virtual returnValue times (const Indexlist *const irows, const Indexlist *const icols, int xN, real_t alpha, const real_t *x, int xLD, real_t beta, real_t *y, int yLD, BooleanType yCompr=BT_TRUE) const
returnValue transTimes (int xN, real_t alpha, const real_t *x, int xLD, real_t beta, real_t *y, int yLD) const
virtual returnValue transTimes (const Indexlist *const irows, const Indexlist *const icols, int xN, real_t alpha, const real_t *x, int xLD, real_t beta, real_t *y, int yLD) const
virtual returnValue addToDiag (real_t alpha)
virtual returnValue print () const
BooleanType needToFreeMemory () const
void doFreeMemory ()
void doNotFreeMemory ()
Protected Attributes
int nRows
int nCols
int leaDim
real_t * val
BooleanType freeMemory
Detailed Description
Symmetric dense matrix class.
Author:
Andreas Potschka, Christian Kirches, Hans Joachim Ferreau
Version:
3.0beta
Date:
2011
Constructor & Destructor Documentation
SymDenseMat::SymDenseMat () [inline]
Default constructor.
Referenced by duplicate().
SymDenseMat::SymDenseMat (int m, int n, int lD, real_t * v) [inline]
Constructor from vector of values.
Parameters:
m Number of rows.
n Number of columns.
lD Leading dimension.
v Values.
Member Function Documentation
returnValue DenseMatrix::addToDiag (real_t alpha) [virtual, inherited]
Adds given offset to diagonal of matrix.
Returns:
SUCCESSFUL_RETURN
RET_NO_DIAGONAL_AVAILABLE
Parameters:
alpha Diagonal offset.
Implements Matrix.
References DenseMatrix::leaDim, DenseMatrix::nCols, DenseMatrix::nRows, SUCCESSFUL_RETURN, and DenseMatrix::val.
returnValue SymDenseMat::bilinear (const Indexlist *const icols, int xN, const real_t * x, int xLD, real_t * y, int yLD) const [virtual]
Compute bilinear form y = x'*H*x using submatrix given by index list.
Returns:
SUCCESSFUL_RETURN
Parameters:
icols Index list specifying columns of x.
xN Number of vectors to multiply.
x Input vector to be multiplied (uncompressed).
xLD Leading dimension of input x.
y Output vector of results (compressed).
yLD Leading dimension of output y.
Implements SymmetricMatrix.
References DenseMatrix::leaDim, Indexlist::length, Indexlist::number, real_t, SUCCESSFUL_RETURN, and DenseMatrix::val.
real_t DenseMatrix::diag (int i) const [virtual, inherited]
Returns i-th diagonal entry.
Returns:
i-th diagonal entry
Parameters:
i Index.
Implements Matrix.
References DenseMatrix::leaDim, and DenseMatrix::val.
void Matrix::doFreeMemory () [inline, inherited]
Enables de-allocation of internal memory.
References BT_TRUE, and Matrix::freeMemory.
Referenced by SymSparseMat::duplicate(), SparseMatrixRow::duplicate(), SparseMatrix::duplicate(), duplicate(), DenseMatrix::duplicate(), QProblemB::setupQPdataFromFile(), QProblem::setupQPdataFromFile(), SparseMatrix::SparseMatrix(), and SparseMatrixRow::SparseMatrixRow().
void Matrix::doNotFreeMemory () [inline, inherited]
Disables de-allocation of internal memory.
Referenced by SparseMatrixRow::free(), SparseMatrix::free(), Matrix::Matrix(), SparseMatrix::SparseMatrix(), and SparseMatrixRow::SparseMatrixRow().
Matrix * SymDenseMat::duplicate () const [virtual]
Returns a deep-copy of the Matrix object.
Returns:
Deep-copy of Matrix object
Reimplemented from DenseMatrix.
References BT_TRUE, Matrix::doFreeMemory(), DenseMatrix::nCols, Matrix::needToFreeMemory(), DenseMatrix::nRows, real_t, SymDenseMat(), and DenseMatrix::val.
void DenseMatrix::free () [virtual, inherited]
Frees all internal memory.
Implements Matrix.
References DenseMatrix::val.
Referenced by DenseMatrix::~DenseMatrix().
returnValue DenseMatrix::getCol (int cNum, const Indexlist *const irows, real_t alpha, real_t * col) const [virtual, inherited]
Retrieve indexed entries of matrix column multiplied by alpha.
Returns:
SUCCESSFUL_RETURN
Parameters:
cNum Column number.
irows Index list specifying rows.
alpha Scalar factor.
col Output column vector.
Implements Matrix.
References DenseMatrix::leaDim, Indexlist::length, Indexlist::number, SUCCESSFUL_RETURN, and DenseMatrix::val.
real_t DenseMatrix::getNorm () const [virtual, inherited]
Get the two-norm of the matrix
Returns:
Two-norm of the matrix
Implements Matrix.
References DenseMatrix::nCols, DenseMatrix::nRows, real_t, and DenseMatrix::val.
returnValue DenseMatrix::getRow (int rNum, const Indexlist *const icols, real_t alpha, real_t * row) const [virtual, inherited]
Retrieve indexed entries of matrix row multiplied by alpha.
Returns:
SUCCESSFUL_RETURN
Parameters:
rNum Row number.
icols Index list specifying columns.
alpha Scalar factor.
row Output row vector.
Implements Matrix.
References DenseMatrix::leaDim, Indexlist::length, DenseMatrix::nCols, Indexlist::number, SUCCESSFUL_RETURN, and DenseMatrix::val.
real_t DenseMatrix::getRowNorm (int rNum) const [virtual, inherited]
Get the two-norm of a row
Returns:
Two-norm of row rNum
Implements Matrix.
References DenseMatrix::leaDim, DenseMatrix::nCols, real_t, and DenseMatrix::val.
BooleanType DenseMatrix::isDiag () const [virtual, inherited]
Checks whether matrix is square and diagonal.
Returns:
BT_TRUE iff matrix is square and diagonal;
BT_FALSE otherwise.
Implements Matrix.
References BT_FALSE, BT_TRUE, EPS, DenseMatrix::leaDim, DenseMatrix::nCols, DenseMatrix::nRows, and DenseMatrix::val.
BooleanType Matrix::needToFreeMemory () const [inline, inherited]
Returns whether internal memory needs to be de-allocated.
Returns:
BT_TRUE iff internal memory needs to be de-allocated,
BT_FALSE otherwise
References Matrix::freeMemory.
Referenced by duplicate(), DenseMatrix::duplicate(), DenseMatrix::~DenseMatrix(), SparseMatrix::~SparseMatrix(), and SparseMatrixRow::~SparseMatrixRow().
returnValue DenseMatrix::print () const [virtual, inherited]
Prints matrix to screen.
Returns:
SUCCESSFUL_RETURN
Implements Matrix.
References DenseMatrix::nCols, DenseMatrix::nRows, and DenseMatrix::val.
returnValue DenseMatrix::times (const Indexlist *const irows, const Indexlist *const icols, int xN, real_t alpha, const real_t * x, int xLD, real_t beta, real_t * y, int yLD, BooleanType yCompr = BT_TRUE) const [virtual, inherited]
Evaluate matrix vector product with submatrix given by Indexlist.
Returns:
SUCCESSFUL_RETURN
Parameters:
irows Index list specifying rows.
icols Index list specifying columns.
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
yCompr Compressed storage for y.
Implements Matrix.
References BT_TRUE, Indexlist::iSort, DenseMatrix::leaDim, Indexlist::length, DenseMatrix::nCols, Indexlist::number, SUCCESSFUL_RETURN, and DenseMatrix::val.
returnValue DenseMatrix::times (int xN, real_t alpha, const real_t * x, int xLD, real_t beta, real_t * y, int yLD) const [virtual, inherited]
Evaluate Y=alpha*A*X + beta*Y.
Returns:
SUCCESSFUL_RETURN.
Parameters:
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
Implements Matrix.
References GEMM, getMax(), DenseMatrix::nCols, NOTRANS, DenseMatrix::nRows, SUCCESSFUL_RETURN, TRANS, and DenseMatrix::val.
returnValue DenseMatrix::transTimes (const Indexlist *const irows, const Indexlist *const icols, int xN, real_t alpha, const real_t * x, int xLD, real_t beta, real_t * y, int yLD) const [virtual, inherited]
Evaluate matrix transpose vector product.
Returns:
SUCCESSFUL_RETURN
Parameters:
irows Index list specifying rows.
icols Index list specifying columns.
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
Implements Matrix.
References Indexlist::iSort, DenseMatrix::leaDim, Indexlist::length, Indexlist::number, SUCCESSFUL_RETURN, and DenseMatrix::val.
returnValue DenseMatrix::transTimes (int xN, real_t alpha, const real_t * x, int xLD, real_t beta, real_t * y, int yLD) const [virtual, inherited]
Evaluate Y=alpha*A'*X + beta*Y.
Returns:
SUCCESSFUL_RETURN.
Parameters:
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
Implements Matrix.
References GEMM, getMax(), DenseMatrix::nCols, NOTRANS, DenseMatrix::nRows, SUCCESSFUL_RETURN, and DenseMatrix::val.
Member Data Documentation
BooleanType Matrix::freeMemory [protected, inherited]
Indicating whether internal memory needs to be de-allocated.
Referenced by Matrix::doFreeMemory(), and Matrix::needToFreeMemory().
int DenseMatrix::leaDim [protected, inherited]
Leading dimension.
Referenced by DenseMatrix::addToDiag(), bilinear(), DenseMatrix::diag(), DenseMatrix::getCol(), DenseMatrix::getRow(), DenseMatrix::getRowNorm(), DenseMatrix::isDiag(), DenseMatrix::times(), and DenseMatrix::transTimes().
int DenseMatrix::nCols [protected, inherited]
Number of columns.
Referenced by DenseMatrix::addToDiag(), duplicate(), DenseMatrix::duplicate(), DenseMatrix::getNorm(), DenseMatrix::getRow(), DenseMatrix::getRowNorm(), DenseMatrix::isDiag(), DenseMatrix::print(), DenseMatrix::times(), and DenseMatrix::transTimes().
int DenseMatrix::nRows [protected, inherited]
Number of rows.
Referenced by DenseMatrix::addToDiag(), duplicate(), DenseMatrix::duplicate(), DenseMatrix::getNorm(), DenseMatrix::isDiag(), DenseMatrix::print(), DenseMatrix::times(), and DenseMatrix::transTimes().
real_t* DenseMatrix::val [protected, inherited]
Vector of entries.
Referenced by DenseMatrix::addToDiag(), bilinear(), DenseMatrix::diag(), duplicate(), DenseMatrix::duplicate(), DenseMatrix::free(), DenseMatrix::getCol(), DenseMatrix::getNorm(), DenseMatrix::getRow(), DenseMatrix::getRowNorm(), DenseMatrix::isDiag(), DenseMatrix::print(), DenseMatrix::times(), and DenseMatrix::transTimes().
The documentation for this class was generated from the following files:
include/qpOASES/Matrices.hpp
src/Matrices.cpp