qpOASES3.0beta: Indexlist Class Reference
Indexlist Class Reference
Stores and manages index lists.
#include <Indexlist.hpp>
Public Member Functions
Indexlist ()
Indexlist (int n)
Indexlist (const Indexlist &rhs)
~Indexlist ()
Indexlist & operator= (const Indexlist &rhs)
returnValue init (int n=0)
returnValue getNumberArray (int **const numberarray) const
int getIndex (int givennumber) const
int getNumber (int physicalindex) const
int getLength () const
int getLastNumber () const
returnValue addNumber (int addnumber)
returnValue removeNumber (int removenumber)
returnValue swapNumbers (int number1, int number2)
BooleanType isMember (int _number) const
Protected Member Functions
returnValue clear ()
returnValue copy (const Indexlist &rhs)
int findInsert (int i) const
Protected Attributes
int * number
int * iSort
int length
int first
int last
int lastusedindex
int physicallength
Friends
class DenseMatrix
class SymDenseMat
class SparseMatrix
class SparseMatrixRow
class SymSparseMat
Detailed Description
This class manages index lists of active/inactive bounds/constraints.
Author:
Hans Joachim Ferreau
Version:
3.0beta
Date:
2007-2012
Constructor & Destructor Documentation
BEGIN_NAMESPACE_QPOASES Indexlist::Indexlist ()
Default constructor.
References init(), iSort, and number.
Indexlist::Indexlist (int n)
Constructor which takes the desired physical length of the index list.
Parameters:
n Physical length of index list.
References init(), iSort, and number.
Indexlist::Indexlist (const Indexlist & rhs)
Copy constructor (deep copy).
Parameters:
rhs Rhs object.
References copy().
Indexlist::~Indexlist ()
Destructor.
References clear().
Member Function Documentation
returnValue Indexlist::addNumber (int addnumber)
Adds number to index list.
Returns:
SUCCESSFUL_RETURN
RET_INDEXLIST_MUST_BE_REORDERD
RET_INDEXLIST_EXCEEDS_MAX_LENGTH
Parameters:
addnumber Number to be added.
References findInsert(), iSort, length, number, physicallength, RET_INDEXLIST_EXCEEDS_MAX_LENGTH, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by SubjectTo::addIndex(), Constraints::rotate(), Bounds::rotate(), Constraints::shift(), and Bounds::shift().
returnValue Indexlist::clear () [protected]
Frees all allocated memory.
Returns:
SUCCESSFUL_RETURN
References iSort, number, and SUCCESSFUL_RETURN.
Referenced by init(), operator=(), and ~Indexlist().
returnValue Indexlist::copy (const Indexlist & rhs) [protected]
Copies all members from given rhs object.
Returns:
SUCCESSFUL_RETURN
Parameters:
rhs Rhs object.
References iSort, length, number, physicallength, and SUCCESSFUL_RETURN.
Referenced by Indexlist(), and operator=().
int Indexlist::findInsert (int i) const [protected]
Find first index j between -1 and length in sorted list of indices iSort such that numbers[iSort[j]] <= i < numbers[iSort[j+1]]. Uses bisection.
Returns:
j.
References iSort, length, and number.
Referenced by addNumber(), getIndex(), removeNumber(), and swapNumbers().
int Indexlist::getIndex (int givennumber) const
Determines the index within the index list at with a given number is stored.
Returns:
>= 0: Index of given number.
-1: Number not found.
Parameters:
givennumber Number whose index shall be determined.
References findInsert(), iSort, and number.
Referenced by QProblemB::addBound(), isMember(), and QProblem::removeConstraint().
int Indexlist::getLastNumber () const [inline]
Returns last number within the index list.
Returns:
Last number within the index list.
References length, and number.
Referenced by QProblem::addBound().
int Indexlist::getLength () const [inline]
Returns the current length of the index list.
Returns:
Current length of the index list.
References length.
Referenced by Constraints::getNAC(), Bounds::getNFR(), Bounds::getNFX(), Constraints::getNIAC(), and QProblem::setupCholeskyDecompositionProjected().
BEGIN_NAMESPACE_QPOASES int Indexlist::getNumber (int physicalindex) const [inline]
Returns the number stored at a given physical index.
Returns:
>= 0: Number stored at given physical index.
-RET_INDEXLIST_OUTOFBOUNDS
Parameters:
physicalindex Physical index of the number to be returned.
References length, number, and RET_INDEXLIST_OUTOFBOUNDS.
returnValue Indexlist::getNumberArray (int **const numberarray) const
Creates an array of all numbers within the index set in correct order.
Returns:
SUCCESSFUL_RETURN
RET_INDEXLIST_CORRUPTED
Parameters:
numberarray Output: Array of numbers (NULL on error).
References number, RET_INVALID_ARGUMENTS, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by QProblem::addBound(), QProblem::addBound_ensureLI(), QProblem::addConstraint(), QProblem::addConstraint_checkLI(), QProblem::addConstraint_ensureLI(), QProblemB::determineDataShift(), QProblem::determineDataShift(), QProblemB::determineStepDirection(), QProblem::determineStepDirection(), QProblem::dropInfeasibles(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getVarianceCovariance(), QProblemB::performStep(), QProblem::performStep(), Constraints::print(), Bounds::print(), QProblemB::removeBound(), QProblem::removeBound(), QProblem::removeConstraint(), QProblemB::setupCholeskyDecomposition(), QProblem::setupCholeskyDecompositionProjected(), QProblem::setupTQfactorisation(), and QProblem::solveCurrentEQP().
returnValue Indexlist::init (int n = 0)
Initialises index list of desired physical length.
Returns:
SUCCESSFUL_RETURN
RET_INVALID_ARGUMENTS
Parameters:
n Physical length of index list.
References clear(), iSort, length, number, physicallength, RET_INVALID_ARGUMENTS, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by Indexlist(), Constraints::init(), and Bounds::init().
BooleanType Indexlist::isMember (int _number) const [inline]
Determines if a given number is contained in the index set.
Returns:
BT_TRUE iff number is contain in the index set
Parameters:
_number Number to be tested for membership.
References BT_FALSE, BT_TRUE, and getIndex().
Indexlist & Indexlist::operator= (const Indexlist & rhs)
Assingment operator (deep copy).
Parameters:
rhs Rhs object.
References clear(), and copy().
returnValue Indexlist::removeNumber (int removenumber)
Removes number from index list.
Returns:
SUCCESSFUL_RETURN
Parameters:
removenumber Number to be removed.
References findInsert(), iSort, length, number, and SUCCESSFUL_RETURN.
Referenced by SubjectTo::removeIndex().
returnValue Indexlist::swapNumbers (int number1, int number2)
Swaps two numbers within index list.
Returns:
SUCCESSFUL_RETURN
Parameters:
number1 First number for swapping.
number2 Second number for swapping.
References findInsert(), iSort, number, RET_INDEXLIST_CORRUPTED, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by SubjectTo::swapIndex().
Member Data Documentation
int Indexlist::first [protected]
Physical index of first element.
int* Indexlist::iSort [protected]
Index list to sort vector number
Referenced by addNumber(), SymSparseMat::bilinear(), clear(), copy(), findInsert(), SparseMatrixRow::getCol(), SparseMatrix::getCol(), getIndex(), SparseMatrixRow::getRow(), SparseMatrix::getRow(), Indexlist(), init(), removeNumber(), swapNumbers(), SparseMatrixRow::times(), SparseMatrix::times(), DenseMatrix::times(), SparseMatrixRow::transTimes(), SparseMatrix::transTimes(), and DenseMatrix::transTimes().
int Indexlist::last [protected]
Physical index of last element.
int Indexlist::lastusedindex [protected]
Physical index of last entry in index list.
int Indexlist::length [protected]
Length of index list.
Referenced by addNumber(), SymSparseMat::bilinear(), SymDenseMat::bilinear(), copy(), findInsert(), SparseMatrixRow::getCol(), DenseMatrix::getCol(), getLastNumber(), getLength(), getNumber(), SparseMatrix::getRow(), DenseMatrix::getRow(), init(), removeNumber(), SparseMatrixRow::times(), SparseMatrix::times(), DenseMatrix::times(), SparseMatrixRow::transTimes(), SparseMatrix::transTimes(), and DenseMatrix::transTimes().
int* Indexlist::number [protected]
Array to store numbers of constraints or bounds.
Referenced by addNumber(), SymSparseMat::bilinear(), SymDenseMat::bilinear(), clear(), copy(), findInsert(), SparseMatrixRow::getCol(), SparseMatrix::getCol(), DenseMatrix::getCol(), getIndex(), getLastNumber(), getNumber(), getNumberArray(), SparseMatrixRow::getRow(), SparseMatrix::getRow(), DenseMatrix::getRow(), Indexlist(), init(), removeNumber(), swapNumbers(), SparseMatrixRow::times(), SparseMatrix::times(), DenseMatrix::times(), SparseMatrixRow::transTimes(), SparseMatrix::transTimes(), and DenseMatrix::transTimes().
int Indexlist::physicallength [protected]
Physical length of index list.
Referenced by addNumber(), copy(), and init().
The documentation for this class was generated from the following files:
include/qpOASES/Indexlist.hpp
src/Indexlist.cpp
include/qpOASES/Indexlist.ipp