qpOASES3.0beta: src/MessageHandling.cpp File Reference
src/MessageHandling.cpp File Reference
#include <stdio.h>
#include <qpOASES/MessageHandling.hpp>
#include <qpOASES/Utils.hpp>
Functions
MessageHandling * getGlobalMessageHandler ()
Variables
BEGIN_NAMESPACE_QPOASES
MessageHandling::ReturnValueList returnValueList []
MessageHandling globalMessageHandler (stderr, VS_VISIBLE, VS_VISIBLE, VS_VISIBLE)
Detailed Description
Author:
Hans Joachim Ferreau, Andreas Potschka, Christian Kirches
Version:
3.0beta
Date:
2007-2012
Implementation of the MessageHandling class including global return values.
Function Documentation
MessageHandling* getGlobalMessageHandler ()
Returns a pointer to global message handler.
Returns:
Pointer to global message handler.
References globalMessageHandler.
Referenced by QProblem::addBound_ensureLI(), QProblem::addConstraint_ensureLI(), QProblemB::changeActiveSet(), QProblem::changeActiveSet(), myPrintf(), QProblemB::performStep(), QProblem::performStep(), QProblemB::QProblemB(), readFromFile(), QProblemB::setPrintLevel(), QProblemB::solveQP(), QProblem::solveQP(), writeIntoFile(), and QProblemB::~QProblemB().
Variable Documentation
MessageHandling globalMessageHandler(stderr, VS_VISIBLE, VS_VISIBLE, VS_VISIBLE)
Global message handler for all qpOASES modules.
Referenced by getGlobalMessageHandler().
BEGIN_NAMESPACE_QPOASES MessageHandling::ReturnValueList returnValueList[]
Defines pairs of global return values and messages.